[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[forms]
  contact:
    name = "contact" 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 